package org.omg.PortableServer;


/**
* org/omg/PortableServer/ID_ASSIGNMENT_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u112/7935/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Friday, September 30, 2016 10:43:20 PM PDT
*/

public interface ID_ASSIGNMENT_POLICY_ID
{

  /**
  	 * The value representing ID_ASSIGNMENT_POLICY_ID.
  	 */
  public static final int value = (int)(19L);
}
